language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - alu0100819847@ull.edu.es

script:
  #Test unitario y de integracion en perfil DEV, con cobertura
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  #SONAR
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=iwvg-upm -Dsonar.login=$SONAR
  #Deploy https://carlos-castro-g-ecosystem.herokuapp.com/api

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master
  app: carlos-castro-g-ecosystem